### ISSUE TITLE
Standalone.xml not working

### ISSUE THREAD

**Issue by guerrerj97** [Onto-Med/OntoBrowser-Docker#1]
Hi @ChristophB, do you mind updating the standalone.xml file under the frontend folder? it seems that it's using some old dependencies. Thank you so much

**Comment by ChristophB** [comment]
Thanks for the notice! The `standalone.xml` file seems to be unsupported by wildfly:latest. I fixed the image version to 10.1.0.Final. The containers should be working again.

Best regards.
